name: alertmanager-deploys
on:
  push:
    branches: 
      - master
      
jobs:
  master:
    # dont run when commit message contain [skip-ci]
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a multi line
        run: |
          echo "starting"
          echo "${GITHUB_RUN_ID}"
          echo "finished"
