# https://docs.github.com/en/actions/hosting-your-own-runners
name: examples
on:
  push:
    branches: 
      - master

jobs:
  master:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    # this will run on a self hosted runner
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a single line
        run: echo "examples was modified"
