# add in first heading
# awesome-<name> [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome) [<!--lint ignore no-dead-urls-->![GitHub Actions status | ruanbekker/awesome-tools](https://github.com/ruanbekker/awesome-tools/workflows/Lint%20Awesome%20List/badge.svg)](https://github.com/ruanbekker/awesome-tools/actions?workflow=Lint+Awesome+List)
name: Lint Awesome List
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: max/awesome-lint@v2.0.0
