# docs: https://github.com/marketplace/actions/build-and-push-docker-images#repository
name: push-to-docker-hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push docker images
      uses: docker/build-push-action@v2
      with:
        context: ./devopstools
        file: ./devopstools/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ruanbekker/devopstools:v1.0.1

