name: examples
on:
  push:
    branches: 
      - master
    paths:
      - 'examples/*.yml'

jobs:
  master:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a single line
        run: echo "examples was modified"
