# examples:
# https://github.com/onedr0p/exportarr/blob/master/.github/workflows/main.yml
name: main
on:
  push:
    branches: 
      - master

jobs:
  master:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a single line
        run: echo "${DUMMY_SECRET}"
        env:
          DUMMY_SECRET: ${{ secrets.DUMMY_SECRET }}

      - name: run a multi line
        run: |
          echo "starting" && \
          echo "${DUMMY_SECRET}" && \
          echo "finished"
